services:
  redis:
    container_name: redis
    image: redis:latest
    command: redis-server
    ports:
      - 6379:6379
  server:
    container_name: server
    build:
      dockerfile: Dockerfile
      context: .
    depends_on:
      - redis
    ports:
      - "8080:8080"